# -*- coding: utf-8 -*-
"""App-Ecommerce (Ejercicio4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PKtZ7E7cqlmC4uC_DyLF0K4bkEoHz8qU
"""

# Comprueba tus links antes de entregar
#repo_url = ""   # Ej: "https://github.com/tu-usuario/tu-app"
#app_url  = ""   # Ej: "https://tu-usuario-tu-app.hf.space"

#print(f"Repositorio:   {repo_url}")
#print(f"App desplegada: {app_url}")

#assert repo_url.startswith("https://github.com/"), "❌ El link del repo no parece correcto"
#assert app_url.startswith("https://"), "❌ El link de la app no parece correcto"
#print("✅ Links con formato correcto — recuerda comprobar que son públicos y accesibles")

"""# README.TXT
# mi-app

## Descripción del Proyecto
Este proyecto es una aplicación web interactiva de e-commerce con IA, construida para permitir a los usuarios categorizar imágenes de productos y obtener información relevante a través de un asistente de chat impulsado por inteligencia artificial. La aplicación integra funcionalidades de clasificación de imágenes, procesamiento de lenguaje natural y una experiencia de usuario que simula la interacción en una plataforma de comercio electrónico, incluyendo la selección de productos y la adición (simulada) al carrito.

## Tecnologías Utilizadas
*   **Frontend/Interfaz:** Gradio (gr.Blocks, gr.Image, gr.Textbox, gr.Button, gr.Chatbot, gr.CheckboxGroup) para la construcción de la interfaz de usuario.
*   **Clasificación de Imágenes:** Modelos de Hugging Face Transformers (`google/vit-base-patch16-224`) para la categorización automática de imágenes de productos.
*   **Modelo de Lenguaje (LLM):** Google Gemini (`gemini-2.5-flash`) para las capacidades de conversación del chatbot.
*   **Manejo de Datos:** La librería Pandas se utiliza para la gestión y manipulación de la base de datos de productos.
*   **Entorno de Desarrollo y Despliegue:** Google Colab para el desarrollo inicial y Hugging Face Spaces / Streamlit Cloud para el despliegue online.

## Funcionalidades Clave
La aplicación se compone de los siguientes módulos principales:

### 1. Base de Datos de Productos
Una colección predefinida de productos (laptops, monitores, periféricos) con detalles como modelo, precio, stock y descripción, que sirve como fuente de información para el asistente de chat.

### 2. Módulo de Categorización de Imágenes
Permite a los usuarios subir una imagen de un producto. Un modelo de IA clasifica la imagen en una de las categorías predefinidas (`laptop`, `monitor`, `perifericos`). El usuario puede borrar la imagen o usar la categoría predicha para interactuar con el chatbot.

### 3. Asistente de Información de Productos (Chatbot)
Un asistente conversacional que interactúa con el usuario y proporciona información basada en el contexto:
*   **Respuestas Generales:** Utiliza Google Gemini para responder preguntas abiertas.
*   **Respuestas Contextualizadas:** Si una imagen ha sido categorizada, el chatbot ofrece listar los productos de esa categoría.
*   **Selección de Productos:** Presenta los modelos disponibles de una categoría en un formato seleccionable (checkboxes) y simula la adición de productos al carrito.

## Instalación y Ejecución Local

### Prerrequisitos
*   Python 3.8+
*   Clave API de Google Gemini (configurada como secreto de entorno `GEMINI_API_KEY`)

### Pasos
1.  Clona el repositorio:
    ```bash
    git clone https://github.com/tu-usuario/mi-app.git
    cd mi-app
    ```
2.  Crea un entorno virtual (recomendado):
    ```bash
    python -m venv venv
    source venv/bin/activate # En Windows usa `venv\Scripts\activate`
    ```
3.  Instala las dependencias:
    ```bash
    pip install -r requirements.txt
    ```
    (Asegúrate de que `requirements.txt` contenga `gradio==3.50.2`, `transformers`, `accelerate`, `torch`, `google-generativeai`, `pandas`)
4.  Configura tu clave API de Gemini:
    Asegúrate de tener tu `GEMINI_API_KEY` configurada como una variable de entorno. Por ejemplo:
    ```bash
    export GEMINI_API_KEY='tu_clave_aqui'
    # O si usas Colab/Hugging Face Spaces, configura como un 'Secret'.
    ```
5.  Ejecuta la aplicación:
    ```bash
    python app.py
    ```
    (Si estás en Colab, simplemente ejecuta las celdas del notebook).

## Despliegue Online

La aplicación está diseñada para ser fácilmente desplegable en plataformas como Hugging Face Spaces o Streamlit Cloud.

### Hugging Face Spaces
1.  Crea un nuevo Space en Hugging Face.
2.  Conecta tu repositorio GitHub.
3.  Asegúrate de que tu `requirements.txt` esté correcto.
4.  Configura `GEMINI_API_KEY` como un secreto de entorno en tu Space.

**Link a la App Desplegada:** [URL de tu aplicación desplegada aquí]

## Capturas de Pantalla
(Añade aquí capturas de pantalla de tu aplicación funcionando, mostrando la categorización de imágenes, la interacción del chatbot y la selección de productos).

**Ejemplo:**

![Captura de pantalla de la interfaz principal]

![Captura de pantalla de la interacción del chatbot]

"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# gradio==3.50.2
# transformers
# accelerate
# torch
# google-generativeai
# pandas==2.2.2
# pillow

"""### Instalación de librerías
Primero, instalaremos las librerías necesarias para la aplicación: `gradio` y `transformers` para los modelos de Hugging Face.
"""

import sys

# Uninstall potentially conflicting numpy and pandas to ensure a clean slate
!{sys.executable} -m pip uninstall numpy pandas -y --quiet

# Install all dependencies from requirements.txt, which includes compatible numpy/pandas
!{sys.executable} -m pip install -r requirements.txt --quiet

# Para evitar advertencias de tokenizers
import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"

"""### 1. Base de datos de E-commerce
Definiremos la base de datos de productos en un diccionario Python. Esta será la fuente de información para el chatbot.
"""

ecommerce_products = [
    # Laptops
    {
        "categoria": "laptop",
        "modelo": "Dell XPS 15",
        "precio": 1500,
        "stock": 10,
        "descripcion": "Portátil potente con pantalla de alta resolución y rendimiento excepcional para profesionales.",
    },
    {
        "categoria": "laptop",
        "modelo": "MacBook Air M2",
        "precio": 1300,
        "stock": 15,
        "descripcion": "Diseño ultradelgado, chip M2 eficiente, ideal para productividad y creatividad en movimiento.",
    },
    {
        "categoria": "laptop",
        "modelo": "HP Spectre x360",
        "precio": 1400,
        "stock": 8,
        "descripcion": "Convertible 2 en 1 con gran versatilidad y diseño elegante, perfecto para trabajo y ocio.",
    },
    {
        "categoria": "laptop",
        "modelo": "Lenovo ThinkPad X1 Carbon",
        "precio": 1600,
        "stock": 7,
        "descripcion": "Laptop empresarial duradera y ligera, con teclado legendario y excelentes características de seguridad.",
    },
    {
        "categoria": "laptop",
        "modelo": "Asus ROG Zephyrus G14",
        "precio": 1800,
        "stock": 5,
        "descripcion": "Portátil gaming compacto y potente, con excelente rendimiento para juegos y creación de contenido.",
    },
    # Monitores
    {
        "categoria": "monitor",
        "modelo": "LG UltraGear 27GP850-B",
        "precio": 450,
        "stock": 12,
        "descripcion": "Monitor gaming de 27 pulgadas, 1440p, 165Hz con tiempo de respuesta rápido y colores vibrantes.",
    },
    {
        "categoria": "monitor",
        "modelo": "Dell UltraSharp U2723QE",
        "precio": 600,
        "stock": 9,
        "descripcion": "Monitor 4K de 27 pulgadas con excelente precisión de color y conectividad USB-C, ideal para profesionales.",
    },
    {
        "categoria": "monitor",
        "modelo": "Samsung Odyssey G7",
        "precio": 700,
        "stock": 6,
        "descripcion": "Monitor curvo de 32 pulgadas, 1440p, 240Hz, diseñado para una experiencia de juego inmersiva.",
    },
    # Periféricos
    {
        "categoria": "perifericos",
        "modelo": "Logitech MX Master 3S",
        "precio": 100,
        "stock": 20,
        "descripcion": "Ratón ergonómico avanzado con desplazamiento MagSpeed, ideal para productividad y control preciso.",
    },
    {
        "categoria": "perifericos",
        "modelo": "HyperX Cloud II",
        "precio": 80,
        "stock": 25,
        "descripcion": "Auriculares gaming cómodos con sonido envolvente 7.1 y micrófono con cancelación de ruido.",
    },
]

# Variable global para almacenar la categoría predicha
predicted_image_category = None

import pandas as pd

df_products = pd.DataFrame(ecommerce_products)
display(df_products)

"""### 2. Módulo de Carga de Imágenes y Categorización
Este módulo permitirá al usuario subir una imagen. Un modelo de clasificación de imágenes de Hugging Face la categorizará, y el resultado se mostrará y se almacenará para el chatbot.
"""

import gradio as gr
from transformers import pipeline
from PIL import Image
import torch

# Cargar el modelo de clasificación de imágenes de Hugging Face
# Usamos un modelo general y luego mapeamos las etiquetas a nuestras categorías
image_classifier = pipeline("image-classification", model="google/vit-base-patch16-224", device=0 if torch.cuda.is_available() else -1)

def classify_image(image: Image.Image):
    global predicted_image_category
    if image is None:
        predicted_image_category = None
        return "Por favor, sube una imagen para categorizar."

    # Clasificar la imagen
    predictions = image_classifier(image)
    top_prediction = predictions[0]["label"].lower()

    # Mapear las etiquetas del modelo a nuestras categorías de e-commerce
    if any(keyword in top_prediction for keyword in ["laptop", "notebook", "computer", "pc"]):
        category = "laptop"
    elif any(keyword in top_prediction for keyword in ["monitor", "display", "screen"]):
        category = "monitor"
    elif any(keyword in top_prediction for keyword in ["mouse", "keyboard", "headset", "peripherals", "usb"]):
        category = "perifericos"
    else:
        category = "No se pudo categorizar con precisión (resultado del modelo: " + top_prediction + ")"

    predicted_image_category = category
    return f"La imagen ha sido categorizada como: **{category.capitalize()}** (Predicción original: {top_prediction})"

"""### 3. Chat de Información de Productos
Esta ventana de chat interactuará con el usuario. Si el usuario pregunta por la categoría de la imagen subida, el chatbot buscará y presentará los productos relevantes de nuestra base de datos.
"""

def format_products_as_table(category):
    filtered_products = [p for p in ecommerce_products if p["categoria"] == category]
    if not filtered_products:
        return "No se encontraron productos para esta categoría."

    table_header = "| Categoría | Modelo | Precio | Stock | Descripción |\n|---|---|---|---|---|\n"
    table_rows = []
    for p in filtered_products:
        table_rows.append(f"| {p['categoria'].capitalize()} | {p['modelo']} | {p['precio']}\u20ac | {p['stock']} | {p['descripcion']} |")

    return table_header + "\n".join(table_rows)

def get_product_models_for_category(category):
    """Returns a list of product model names for a given category."""
    filtered_products = [p for p in ecommerce_products if p["categoria"] == category]
    return [p["modelo"] for p in filtered_products]

def chat_response(message, history):
    global predicted_image_category # Access the global variable

    user_message_lower = message.lower()
    last_bot_message_lower = ""
    if history and history[-1][1]: # Check if there's a last bot message
        last_bot_message_lower = history[-1][1].lower()

    # Default values for product selection components (hidden and empty)
    product_choices = []
    product_selection_visible = False
    add_to_cart_visible = False

    response_text = "" # Initialize response_text

    # Scenario 1: User responded to the "Quieres consultar opciones?" prompt
    if "¿quieres consultar las opciones disponibles para la categoría?" in last_bot_message_lower:
        if any(keyword in user_message_lower for keyword in ["no", "no quiero", "gracias", "cancelar", "no me interesa"]):
            response_text = "Muy bien, puedes volver a subir otra imagen. Que tengas buen día!!!"
        elif any(keyword in user_message_lower for keyword in ["si", "sí", "quiero", "interesa", "por favor"]):
            if predicted_image_category and predicted_image_category != "No se pudo categorizar con precisión":
                product_choices = get_product_models_for_category(predicted_image_category)
                if product_choices:
                    response_text = f"Claro, aquí tienes los productos para la categoría '{predicted_image_category.capitalize()}'. Por favor, selecciona los que desees agregar al carrito a continuación:"
                    product_selection_visible = True
                    add_to_cart_visible = True
                else:
                    response_text = f"No se encontraron productos para la categoría '{predicted_image_category.capitalize()}' del producto categorizado."
            else:
                response_text = "Lo siento, no tengo una categoría de imagen reciente para consultar. Por favor, primero sube y categoriza una imagen."

        return response_text, product_choices, product_selection_visible, add_to_cart_visible

    # Scenario 2: User explicitly asks for image category info
    if "informacion" in user_message_lower and "categoria" in user_message_lower and "imagen" in user_message_lower:
        if predicted_image_category and predicted_image_category != "No se pudo categorizar con precisión":
            product_choices = get_product_models_for_category(predicted_image_category)
            if product_choices:
                response_text = f"Claro, aquí tienes los productos para la categoría '{predicted_image_category.capitalize()}'. Por favor, selecciona los que desees agregar al carrito a continuación:"
                product_selection_visible = True
                add_to_cart_visible = True
            else:
                response_text = f"No se encontraron productos para la categoría '{predicted_image_category.capitalize()}' del producto categorizado."
        else:
            response_text = "Lo siento, no tengo una categoría de imagen reciente para consultar. Por favor, primero sube y categoriza una imagen."

        return response_text, product_choices, product_selection_visible, add_to_cart_visible

    # Scenario 3: General Gemini response
    try:
        # Prepare chat history for Gemini in the required format
        gemini_history = []
        for user_msg, model_msg in history:
            if user_msg is not None:
                gemini_history.append({"role": "user", "parts": [user_msg]})
            if model_msg is not None:
                gemini_history.append({"role": "model", "parts": [model_msg]})
        gemini_history.append({"role": "user", "parts": [message]})

        response = gemini_model.generate_content(gemini_history)
        response_text = response.text
    except Exception as e:
        response_text = f"Lo siento, tuve un error al contactar a Gemini: {e}"

    return response_text, product_choices, product_selection_visible, add_to_cart_visible

"""### 4. Integración de Gemini para Respuestas del Chat

Vamos a integrar el modelo Gemini para que el chatbot pueda responder preguntas de forma más avanzada, utilizando conocimiento general y no solo la base de datos de productos.
"""

# Importar el SDK de Python
import google.generativeai as genai
# Utilizado para almacenar de forma segura tu clave API
from google.colab import userdata

GEMINI_API_KEY=userdata.get('GEMINI_API_KEY')
genai.configure(api_key=GEMINI_API_KEY)

"""Ahora inicializamos el modelo Gemini."""

# Inicializar el modelo Gemini
gemini_model = genai.GenerativeModel('gemini-2.5-flash')

"""Ahora, modificaremos la función chat_response para usar gemini_model para generar respuestas cuando no se trate de una consulta de categoría de imagen o un saludo."""

def post_categorization_welcome(image_category, chat_history):
    if image_category and "No se pudo categorizar" not in image_category:
        # Extract the actual category name from the output string
        # Assuming image_category is formatted like: "La imagen ha sido categorizada como: **Laptop** (Predicción original: ...)"
        try:
            category_name = image_category.split('**')[1].split('**')[0]
        except IndexError:
            category_name = "la categoría de la imagen"

        welcome_message = f"Hola! La imagen subida corresponde a {category_name}. \u00bfQuieres consultar las opciones disponibles para la categoría?"
        return chat_history + [[None, welcome_message]] # Add a bot message directly
    return chat_history

import gradio as gr

with gr.Blocks(title="App de E-commerce con IA") as demo:
    gr.Markdown("# App de E-commerce con IA")

    # Módulo de Categorización de Imágenes
    with gr.Column(elem_id="image_categorization_section"):
        gr.Markdown("## Módulo de Categorización de Imágenes")
        gr.Markdown("Sube una imagen de un producto (laptop, monitor o periférico) para que sea categorizada por un modelo de IA.")
        image_input = gr.Image(type="pil", label="Sube una imagen de un producto")
        image_output = gr.Textbox(label="Categoría Predicha")
        categorize_button = gr.Button("Categorizar Imagen")
        clear_image_button = gr.Button("Subir una nueva imagen")
        consult_options_button = gr.Button("Consultar opciones disponibles")

        # Function to clear image inputs and reset category
        def clear_image_inputs():
            global predicted_image_category
            predicted_image_category = None
            return None, "" # Clear image_input and image_output

        # Define the action for the categorize button
        categorize_button.click(classify_image, inputs=image_input, outputs=image_output)

        # Link new buttons
        clear_image_button.click(clear_image_inputs, outputs=[image_input, image_output])

    gr.Markdown("--- # --- # --- # ---") # Separador

    # Asistente de Información de Productos (Chat Interface)
    with gr.Column(elem_id="chat_section"):
        gr.Markdown("## Asistente de Información de Productos")
        gr.Markdown("Pregúntame si quieres información sobre la categoría de la última imagen subida (por ejemplo: 'Quiero información sobre la categoría de la imagen').")

        # Now define chatbot here so it's rendered in this section
        chatbot = gr.Chatbot(height=300)

        msg = gr.Textbox(placeholder="Pregúntame sobre la categoría de la imagen subida o sobre los productos.", container=False, scale=7)
        submit_btn = gr.Button("Enviar")

        # Product selection components, initially hidden
        product_selection_checkboxes = gr.CheckboxGroup([], label="Selecciona productos para agregar al carrito", visible=False)
        add_to_cart_btn = gr.Button("Agregar producto(s) seleccionado(s) al carrito", visible=False)

        # Function to handle user message and update chat history for Gradio Blocks
        def user_message_handler(user_message, chat_history):
            # Hide product selection when new message is sent
            return "", chat_history + [[user_message, None]], gr.update(visible=False), gr.update(visible=False)

        # Function to generate bot response and update chat history, including product selection
        def bot_response_wrapper(chat_history):
            if chat_history:
                user_message = chat_history[-1][0] # Get the latest user message
                # chat_response now returns (response_text, product_choices, product_selection_visible, add_to_cart_visible)
                response_text, product_choices, product_selection_visible, add_to_cart_visible = chat_response(user_message, chat_history[:-1])
                chat_history[-1][1] = response_text # Update the latest bot response

            return (
                chat_history,
                gr.update(choices=product_choices, visible=product_selection_visible),
                gr.update(visible=add_to_cart_visible)
            )

        # Function to generate the initial welcome message for the chat
        def post_categorization_welcome(image_category, chat_history):
            if image_category and "No se pudo categorizar" not in image_category:
                category_name = image_category.split('**')[1].split('**')[0]
                welcome_message = f"Hola! La imagen subida corresponde a la categoría \"{category_name}\". \u00bfQuieres consultar las opciones disponibles para la categoría?"
                # This function now needs to return updates for product selection too, but it's only for the initial welcome, so no products yet
                return chat_history + [[None, welcome_message]]
            return chat_history

        # Link the message input and submit button to the chat logic
        msg.submit(user_message_handler, [msg, chatbot], [msg, chatbot, product_selection_checkboxes, add_to_cart_btn], queue=False).then(
            bot_response_wrapper,
            inputs=[chatbot],
            outputs=[chatbot, product_selection_checkboxes, add_to_cart_btn]
        )
        submit_btn.click(user_message_handler, [msg, chatbot], [msg, chatbot, product_selection_checkboxes, add_to_cart_btn], queue=False).then(
            bot_response_wrapper,
            inputs=[chatbot],
            outputs=[chatbot, product_selection_checkboxes, add_to_cart_btn]
        )

        # New handler for the 'Add to Cart' button
        def add_selected_products_to_cart(selected_products, chat_history):
            if not selected_products:
                bot_message = "No has seleccionado ningún producto para agregar al carrito."
            else:
                # Simulate adding to cart - in a real app, this would update a database or session
                cart_items_str = ", ".join(selected_products)
                bot_message = f"¡Perfecto! Se han agregado los siguientes productos al carrito: {cart_items_str}. ¿Hay algo más en lo que pueda ayudarte?"

            chat_history.append([None, bot_message])
            return (
                chat_history,
                gr.update(choices=[], visible=False), # Hide and clear checkboxes
                gr.update(visible=False) # Hide button
            )

        add_to_cart_btn.click(
            add_selected_products_to_cart,
            inputs=[product_selection_checkboxes, chatbot],
            outputs=[chatbot, product_selection_checkboxes, add_to_cart_btn]
        )

    # Move consult_options_button here so it's after the chat_section but still within the Blocks
    # This button needs access to chatbot, so chatbot must be defined before this line.
    with gr.Row(): # Use a Row to group these buttons if you want them on the same line
        # consult_options_button.render() # Removed this line as it causes DuplicateBlockError
        consult_options_button.click(
            post_categorization_welcome,
            inputs=[image_output, chatbot], # image_output for the category, chatbot for history
            outputs=chatbot # Update the chatbot component
        )

demo.launch(share=True)

import gradio
print(gradio.__version__)